### ISSUE TITLE
Non-ASCII Titles cause 500

### ISSUE THREAD

**Issue by awlayton** [Wyvryn/HummingbirdExport#2]
Not sure what all will be helpful. There title that caused the below stack trace was `Kämpfer für die Liebe`.

```
127.0.0.1 - - [22/Jun/2016 16:40:38] "POST /submit HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/awlayton/source/HummingbirdExport/hummingbirdexport/controllers/main.py", line 44, in submit
    xml.write(data)
  File "/home/awlayton/source/HummingbirdExport/hummingbirdexport/controllers/writeMALXML.py", line 38, in write
    self.logger.info("Adding {} with id {}".format(title, mal_id))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128)
```

**Comment by evotopid** [comment]
There is an issue that there is a 500 error sometimes (and no further logs - I know very nice) but usually after a retry it works out (I think it might even be on the api server side).

However in your case the issue seems to be that you are using Python 2.7 which has a different encoding handling than the Python 3.\* language and I don't have the time to support both versions. I will send in a pull request that makes the version 3 explicit, in the meantime you can just edit manage.py's shebang to point to python3.
